FROM gradle:8.0.2-jdk17-alpine
WORKDIR /spring

COPY . .

RUN gradle bootJAR -x test

FROM eclipse-temurin:17-alpine

COPY --from=build /spring/build/libs/restsec-0.0.1-SNAPSHOT.jar /restsec-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", ".\\build\\libs\\safe-api-assignment-SJPaukner-v2-0.0.1-SNAPSHOT.jar"]